### ISSUE TITLE
scopedSlots警告问题

### ISSUE THREAD

**Issue by wjxfhxy** [GitOfZGT/element-tree-line#1]
你好，在vue3.2版本中使用，会报
[Vue warn]: Property "$scopedSlots" was accessed during render but is not defined on instance. 
警告，scopedSlots在vue3中已经取消，不考虑处理一下？

**Comment by mhiStrat** [comment]
> 你好，在vue3.2版本中使用，会报 [Vue warn]: Property "$scopedSlots" was accessed during render but is not defined on instance. 警告，scopedSlots在vue3中已经取消，不考虑处理一下？


老哥，你的这个解决了吗

**Comment by GitOfZGT** [comment]
我个人还在用vue2，我推送了 element-tree-line@0.2.1-alpha ，你看是否已解决vue3的警告，如果解决了我将推送正式 element-tree-line@0.2.1

**Comment by songjiachao** [comment]
已经解决
